version: "3.7"

services:
  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - ./config:/config
      - ./shared:/shared
    ports:
      - 8123

    depends_on:
      - custom-card

  custom-card:
    build:
      context: custom-card
      dockerfile: Dockerfile
    ports:
      - 5000
    volumes:
      - ./custom-card:/app

